data: 
  folder: "./data"
  audio_max_len: 10
  sr: 16000
  split_ratio: [0.8, 0.1, 0.1]

training:
  gpu: True
  batch_size: 32
  num_workers: 8
  lr: 0.0001
  epochs: 100
  model_type: "CNN14"
  pretrain_dir: "./pretrained_model/Cnn14_16k_mAP=0.438.pth"
  save_dir: "./ckpt/best_model.pth"
  scaler_path: "./scaler.ckpt"
  filter_aug: True

CRNN:
  nclass: 4
  activation: "relu"
  dropout: 0.5
  n_RNN_cell: 64
  rnn_layers: 2
  dropout_recurrent: 0
  kernel_size: [3, 3, 3, 3, 3, 3, 3]
  padding: [1, 1, 1, 1, 1, 1, 1]
  stride: [1, 1, 1, 1, 1, 1, 1]
  nb_filters: [ 4, 8, 16, 16, 16, 32, 32]
  pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ] 

feats:
  n_mels: 64
  n_filters: 512
  hop_length: 160
  n_window: 512
  sr: 16000
  f_min: 50
  f_max: 8000
  
