data: 
  audio_folder: "../audio_branch/data"
  audio_max_len: 10
  sr: 32000
  split_ratio: [0.8, 0.1, 0.1]
  text_folder: "../text_branch/data/IEMOCAP"

training:
  model_type: "cat" # ["cat", "attention"]
  scaler_path: "/app/affective_computing/mm_branch/audio_scaler.ckpt"
  save_dir: "/app/affective_computing/mm_branch/ckpt/best_model.pth"
  filter_aug: True
  spec_aug: False
  gpu: True
  batch_size: 16
  num_workers: 6
  lr: 0.0001
  epochs: 20

feats:
  n_mels: 64
  n_filters: 1024
  hop_length: 320
  n_window: 1024
  sr: 32000
  f_min: 50
  f_max: 14000
  
